current:
  major: 1
  minor: 0
  patch: 0
  format: "{$major}.{$minor}.{$patch}"
cache:
  enabled: true
  key: pragmarx-version
  manager: cache # Illuminate\Support\Facades\Cache
build:
  value: # if set overrides command
  command: "git ls-remote {$repository} refs/heads/master"
  repository: "{{ env('APP_GIT_REPOSITORY') }}"
  length: 6
format:
  full: "version {$major}.{$minor}.{$patch} (build {$build})"
  compact: "v. {$major}.{$minor}.{$patch}-{$build}"
  ## add as many formats as you need
